// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCAcSMCgHCr0PrMpj94rxyZ6ikBt13hq1I',
    appId: '1:806907119672:web:5ac3da60550e4b84c13ecd',
    messagingSenderId: '806907119672',
    projectId: 'blb-app-4a9d1',
    authDomain: 'blb-app-4a9d1.firebaseapp.com',
    storageBucket: 'blb-app-4a9d1.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA-iVqOLW0OYLaE7w_FamAWCmkCYx0JKKE',
    appId: '1:806907119672:android:160ab507b770248bc13ecd',
    messagingSenderId: '806907119672',
    projectId: 'blb-app-4a9d1',
    storageBucket: 'blb-app-4a9d1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDIV2PBvvE2AqGAVWQlNWBVQlcD8jQ2Fbo',
    appId: '1:806907119672:ios:c18b5e68f76573bfc13ecd',
    messagingSenderId: '806907119672',
    projectId: 'blb-app-4a9d1',
    storageBucket: 'blb-app-4a9d1.firebasestorage.app',
    androidClientId: '806907119672-vv6if8um2n8lh0q7pn5ftt1lddbogfib.apps.googleusercontent.com',
    iosClientId: '806907119672-331abj7plvuqntt178n1tbf46o1k595v.apps.googleusercontent.com',
    iosBundleId: 'com.example.blb',
  );

}